In [1]:
import tensorflow
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import pickle

In [47]:
## loading the pickle
model = load_model('model.h5')

with open('Label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)


with open('one_hot_encoder_geo.pkl','rb') as file:
    one_hot_encoder_geo = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [48]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [49]:
geo_encoder_new = one_hot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoder_df_new = pd.DataFrame(geo_encoder_new,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))

c:\Users\Kunal\anaconda3\envs\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [50]:
input_data_df = pd.DataFrame([input_data])
input_data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [51]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
Label_encoder_gender  = LabelEncoder()

In [52]:
input_data_df['Gender'] = Label_encoder_gender.fit_transform(input_data_df['Gender'])
input_data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,0,40,3,60000,2,1,1,50000

In [53]:
input_data_df = pd.concat([input_data_df.drop(['Geography'],axis=1),geo_encoder_df_new],axis=1)

In [54]:
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,0,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [57]:
## scalling the data
input_scaler =scaler.transform(input_data_df)
input_scaler

array([[-0.53598516, -1.09499335,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [ ]:
predictation = model.predict(input_scaler)
predictation_prob = predictation[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

np.float32(0.042918745)

In [61]:
print(predictation_prob)

0.042918745

In [62]:
if predictation_prob >0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.